# Container image that runs your code
FROM node:10

COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json
RUN npm install

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY entrypoint.sh /entrypoint.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/entrypoint.sh"]