version: 2.1

jobs:
  build-push-img:
    machine:
      image: ubuntu-2004:202008-01
    # docker:
    #   - image: jdrouet/docker-with-buildx:stable-0.4.2
    steps:
      - checkout
      # - setup_remote_docker:
      #     version: 19.03.13
      - run: docker version
      - run:
          name: Build Docker image
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled

            docker buildx create --name mybuilder --use

            # login
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            
            # build
            docker buildx build \
              --output type=registry \
              --cache-from=type=registry,ref=diveinto/hi-ci-cd:cache \
              --cache-to=type=registry,ref=diveinto/hi-ci-cd:cache,mode=max \
              -t diveinto/hi-ci-cd:latest .
            
            echo '=========================='
            docker images
workflows:
  myworkflow: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build-push-img