version: 2.1

jobs:
  auto-tag:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: auto tag
          command: |
            ./tag.sh -v patch
  build-push-img:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: docker version
      - run:
          name: Build Docker image
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled

            docker buildx create --name mybuilder --use

            # login
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            # build
            docker buildx build \
              --output=type=docker \
              --cache-from=type=registry,ref=diveinto/hi-ci-cd:cache \
              --cache-to=type=registry,ref=diveinto/hi-ci-cd:cache,mode=max \
              -t diveinto/hi-ci-cd:latest .

            echo '=========================='
            docker images

            echo '=========================='
            docker tag diveinto/hi-ci-cd:latest diveinto/hi-ci-cd:$CIRCLE_SHA1

            docker push diveinto/hi-ci-cd:latest
            docker push diveinto/hi-ci-cd:$CIRCLE_SHA1

            if [ "$CIRCLE_TAG" != "" ]
            then
              docker tag  diveinto/hi-ci-cd:latest diveinto/hi-ci-cd:$CIRCLE_TAG
              docker push diveinto/hi-ci-cd:$CIRCLE_TAG
            fi

            echo '=========================='
            docker images
  echo-in-cmd:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: try echo env in heredoc
          command: |
            cat \<<EOF >> k.yaml
            apiVersion: install.kalm.dev/v1alpha1
            kind: KalmOperatorConfig
            metadata:
              namespace: kalm-operator
              name: kalmoperatorconfig-sample
            spec:
              kalmVersion: $CIRCLE_SHA1
            EOF

            cat k.yaml
  update-yaml-using-ruby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: update
          command: |
            mkdir tmp
            cat \<<EOF >> ./tmp/kalm-op-config.yaml
            apiVersion: install.kalm.dev/v1alpha1
            kind: KalmOperatorConfig
            metadata:
              namespace: kalm-operator
              name: kalmoperatorconfig-sample
            spec:
              kalmVersion: $CIRCLE_SHA1
            EOF

            ruby update-kalmop-config.rb foo bar
            ls tmp
            cat ./tmp/updated.yaml
workflows:
  myworkflow: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build-push-img
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*
  2ndworkflow:
    jobs:
      - echo-in-cmd
  3rdworkflow:
    jobs:
      - update-yaml-using-ruby
  auto-tag-workflow:
    jobs:
      - auto-tag
      - build-push-img
          requires:
            - auto-tag
