version: 2.1

jobs:
  build-push-img:
    docker:
      - image: jdrouet/docker-with-buildx:stable-0.4.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker version
      - run:
          name: Build Docker image
          command: |
            docker context list
            echo '==========='
            docker context inspect default
            echo '==========='
            echo $DOCKER_HOST
            echo '==========='
            docker buildx ls

            # docker context create

            # create a builder of docker-container driver type to make use of registry build cache exporter.
            docker buildx create --name mybuilder --use

            # build
            docker buildx ls
workflows:
  myworkflow: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build-push-img