name: auto tag

on:
  push:
    branches:
      - master

jobs:
  job-auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: auto tag
        run: |
          # check if current commit has a tag in format: vx.y.z

          ./tag.sh -v patch
