# https://github.com/marketplace/actions/build-and-push-docker-images#usage

name: build & push img with cache

on:
  push:
    branches: 
      - master
      - build-with-cache

jobs:
  job-build-with-cache:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        uses: actions/checkout@v2

      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-buildx-dir-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile-npm
          tags: diveinto/hi-ci-cd:latest
          cache-from: type=local,src=~/.npm
          cache-to: type=local,dest=~/.npm
      # - 
      #   name: list dir
      #   run: ls -al ~/.npm/* && cat ~/.npm/index.json
      # - 
      #   name: list dir2
      #   run: ls -al ~/.npm/blobs/sha256/* 
      # - 
      #   name: list dir3
      #   run: ls */*