name: CreateFile

on:
  schedule:
    - cron: "* * * * *"

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: echo into file
        run: |
          echo `date` > ./create-file-`date +%s`.txt

      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: setup git identity
        run: |
          git config --global user.email "github-action@no-mail.com"
          git config --global user.name "github-action"
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
